#  Admin::Location
#  Generated by LifeCodeCMS FormAttributes Generator
module Admin
  class Location < Location
    class << self
      def search(params)
        self.all
      end
    end
  end
end