#  Admin::Location
#  Generated by LifeCodeCMS FormAttributes Generator

module Admin
  class Location < Location
    class << self
      def search(params)
        objects = self.all
        if params[:name].present?
          objects = objects.where(name: params[:name])
        end
        if params[:prefecture_code].present?
          objects = objects.where(prefecture_code: params[:prefecture_code])
        end
        if params[:city_code].present?
          objects = objects.where(city_code: params[:city_code])
        end
        objects
      end
    end
  end
end