#  Admin::Location
#  Generated by LifeCodeCMS FormAttributes Generator

module Admin
  class Location < Location
    class << self
      def search(params)
        objects = self.all
        if params[:name].present?
          objects = objects.where(name: params[:name])
        end
        if params[:prefecture_id].present?
          objects = objects.where(prefecture_id: params[:prefecture_id])
        end
        if params[:city_id].present?
          objects = objects.where(city_id: params[:city_id])
        end
        objects
      end
    end
  end
end