---
permission:
  top: '1,2,3'
  articles: '1,2,3'
  inquiries: '1,2,3'
  groups: '1,2'
  locations: '1,2'
  users:
    index: '1,2'
    new: '1,2'
    edit: '1,2,3'
    create: '1,2'
    update: '1,2,3'
    destroy: '1,2,3'
    confirm_user: '1,2,3'
    lock: '1,2'
    resend_confirmation: '1,2'
  events: '1,2,3'
  animals: '1,2,3'
  companies: '1,2,3'
  login_histories: '1,2'